### ISSUE TITLE
配置vscode config时出错

### ISSUE THREAD

**Issue by user-OkuraYusei** [ANA-Training/docs#4]
当尝试使用vscode插件远程连接服务器时，在初始化vscode服务器时停留长时间
<img width="1280" alt="image" src="https://github.com/ANA-Training/docs/assets/144534880/85c705e8-301a-4845-9ab4-62fcb9011c27">
<img width="1280" alt="image" src="https://github.com/ANA-Training/docs/assets/144534880/323b0b16-f1dc-4cf6-979d-ec791eb3776d">

**Comment by abdtyx** [comment]
终端能ssh进去吗？ping一下服务器试试能否ping通

**Comment by abdtyx** [comment]
以及最好目录中不要出现任何中文

**Comment by user-OkuraYusei** [comment]
终端可以 ping通 已经修改用户名为英文 仍然没有解决“”初始化vscode服务器的问题“”
查阅了一些之前的问题 比如有的人把始终显示进程关了莫名就好了 我没有解决
附上config文件
<img width="770" alt="image" src="https://github.com/ANA-Training/docs/assets/144534880/6ca9d880-f7de-44b5-830b-79ffdae7596b">

**Comment by abdtyx** [comment]
ssh配置看起来没问题，但你的路径中似乎还有中文。以及可以看下连接失败的报错信息吗？

**Comment by abdtyx** [comment]
https://blog.csdn.net/suixuejie/article/details/94724022
https://blog.csdn.net/ms961516792/article/details/109050771?spm=1001.2101.3001.6650.1&utm_medium=distribute.pc_relevant.none-task-blog-2%7Edefault%7ECTRLIST%7ERate-1-109050771-blog-94724022.235%5Ev38%5Epc_relevant_anti_t3&depth_1-utm_source=distribute.pc_relevant.none-task-blog-2%7Edefault%7ECTRLIST%7ERate-1-109050771-blog-94724022.235%5Ev38%5Epc_relevant_anti_t3&utm_relevant_index=2
https://support.huaweicloud.com/modelarts_faq/modelarts_05_3117.html
这几个都试过了吗

**Comment by Sakurakoujisekai** [comment]
都试过了 前两个没用 尝试最后一个 建立文件夹，

mkdir: cannot create directory ‘/home/ma-user’: Permission denied

执行 scp -i xxx.pem -P 59999 我不是很理解xxx是什么 看报错觉得是ip地址

scp -i 58.206.101.40.pem -P 59999 "C:\Users\sakurakouji_sekai\Downloads\vscode-server-linux-x64.ta
r.gz" ma-user@58.206.101.40:/home/ma-user/.vscode-server/bin

Warning: Identity file 58.206.101.40.pem not accessible: No such file or directory.
Warning: Identity file 58.206.101.40.pem not accessible: No such file or directory.
ssh: connect to host 58.206.101.40 port 59999: Connection refused
ssh: Could not resolve hostname c: Temporary failure in name resolution

**Comment by Sakurakoujisekai** [comment]
把ma-user替换成我的账号：
scp: /home/yyh2213315503/.vscode-server/bin: No such file or directory
scp: /home/ma-user/.vscode-server/bin: No such file or directory

**Comment by user-OkuraYusei** [comment]
所以我现在在做这样一个事情：
在远程初始化vscode服务器。我把vscode server 删完了然后尝试远程把文件送过去解压
执行成功命令：
rm -rf /home/ma-user/.vscode-server/bin/${commitID}/*

**Comment by abdtyx** [comment]
Sounds good. Wish you good luck:)

**Comment by user-OkuraYusei** [comment]
anyway, even no use.

<img width="1004" alt="image" src="https://github.com/ANA-Training/docs/assets/144534880/7ffd3cfd-0b0c-4993-9cdc-7551dc492677">

**Comment by user-OkuraYusei** [comment]
have any tool to monitor the process? 
i can;t get any details in the picture.
<img width="339" alt="image" src="https://github.com/ANA-Training/docs/assets/144534880/8f3a127f-9dbc-48e6-9fa8-9421c6d4d75f">
