### ISSUE TITLE
task2题目“连续m个服务器”

### ISSUE THREAD

**Issue by ygoconvallaria** [ANA-Training/docs#8]
A1pha在Magic Cloud上有n台服务器，每台服务器有一个固定的算力。为了应对zbc的恶意攻击，A1pha购买了服务器CPU算力升级包。该升级包只能使用一次，但是也可以选择不使用。使用该升级包后，相邻的连续m个服务器的算力将被替换为指定值k。A1pha想知道，如何升级服务器能让收益最大化，即服务器总算力最大。由于可能出现使用升级包后服务器总算力降低或零提升的情况，这种情况下A1pha为了节省经费，会选择不使用升级包，找Magic Cloud退钱。
我对task2题目中的“连续m个服务器”的含义有疑问：对于后继服务器数量不足m个（例如一共n=5,m=3,k=2,我对第四台使用安装包会同时更新第四台和第五台吗？还是更新第四台、第五台、第一台？还是说安装包使用必须保证有m台服务器存在？）

**Comment by abdtyx** [comment]
1. m一定小于n
2. 服务器们均匀分布在一条直线上面，所以连续的m台服务器不可从尾部到达头部
3. 连续的m台服务器与究竟对哪一台服务器使用升级包无关，可以是任意的**连续**m台服务器

**Comment by ygoconvallaria** [comment]
那我可以对后续不足m个的服务器使用升级包吗？就如同我例子中的，对4使用，因为不存在6，所以只会更新4和5对吗？

**Comment by abdtyx** [comment]
不可以。因为连续的m台不仅要连续，还要求必须升级正好m台服务器。

**Comment by ygoconvallaria** [comment]
> 不可以。因为连续的m台不仅要连续，还要求必须升级正好m台服务器。

好的，谢谢您
